name: comedy_assistant
description: An app to assist comedians with their material.
publish_to: 'none' # This prevents accidental publishing

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  record: ^4.4.4
  just_audio: ^0.9.34
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  flutter_markdown: ^0.6.15
  path_provider: ^2.0.15
  package_info_plus: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
